### ISSUE TITLE
Dica: Licença

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-Reabilitacao-Motora#105]
Vejam a compatibilidade das licenças do sistema de vcs..
Sugestão: façam uma seção no readme listando as principais licenças (software relacionado ao sensor, processamento, unity, e o proj de vcs)

**Comment by RomeuCarvalhoAntunes** [comment]
Após reunião com o cliente foi validada a nossa decisão inicial de licença para o projeto.
