### ISSUE TITLE
Traduzir as atas de Dojo e Reunião para markdown

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#112]
### Descrição:
Necessario documentar as atas para ter maior controle do grupo em relação as presenças.

### Critérios de Aceitação
- [ ] Todas as atas em markdown e atualizadas sem nenhum erro

### Tarefas
- [ ] Verificar se todos as atas estão com algum erro de linguagem
- [x] Verificar se todas as atas estão preenchidas
- [x] Completar as atas pendentes
- [ ] Criar uma pasta com cada ata de reuniao e dojo em markdown

**Comment by RomeuCarvalhoAntunes** [comment]
Completei as atas que necessitavam do SM, dei uma olhada rápida em todas, ao meu ver estão completas, no entanto não estão revisadas
