### ISSUE TITLE
Validar os campos de registro de paciente.

### ISSUE THREAD

**Issue by djorkaeffalexandre** [fga-gpp-mds/2018.1-Reabilitacao-Motora#131]
### Descrição:
Validar se os campos de dados estão vazios antes de tentar cadastrar um paciente no banco.

### Critérios de Aceitação
- [ ] Mostrar mensagem que alerta o usuário sobre campo obrigatório.

**Comment by RomeuCarvalhoAntunes** [comment]
Congelada, para refatoração em momento oportuno.
