### ISSUE TITLE
Bug na reprodução de movimento realizado

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-gpp-mds/2018.1-Reabilitacao-Motora#133]
# Bug na reprodução de movimento realizado
---
### Descrição:
O cadastro do movimento já está sendo realizado, porém há problemas na reprodução do mesmo.

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.

- [ ] Movimento reproduzido condizente com realizado

* **Qual o comportamento atual?**
![screenshot_51](https://user-images.githubusercontent.com/23236957/38937155-ea9d59d0-42f8-11e8-851f-8d076d4a34bc.png)

* **Qual o comportamento esperado?**
![screenshot_52](https://user-images.githubusercontent.com/23236957/38937199-05f6d954-42f9-11e8-95e8-17f1e6c6fcd4.png)

* **Qual é a dúvida técnica?**

Bem, a minha implementação segue a seguinte estrutura:
- Dentro de um FixedUpdate, salva cada posiçao (x, y e z) e rotação (x, y e z) -- no worldSpace --, num arquivo.
![screenshot_53](https://user-images.githubusercontent.com/23236957/38937458-a3262f2c-42f9-11e8-9ac8-4f60b187ca30.png)

- Na scene de gráficos, também num fixed update, atualiza a posição da mão, braço, antebraço/cotovelo e ombro de acordo com o que está no arquivo.
![screenshot_55](https://user-images.githubusercontent.com/23236957/38937539-d43a6e98-42f9-11e8-9cf3-0c3c55fa941a.png)

*Obs: eu já coloquei o transform do boneco igual em ambas as cenas (ou seja, tanto na scene Clinic como na scene Graphs, a personagem está na mesma posição e rotação)

Então, o que está de errado? O que eu poderia/deveria mudar? Qual a sugestão de implementação para essa situação?

**Comment by RomeuCarvalhoAntunes** [comment]
@vitorfhc dar uma olhada quando tiver tempo

**Comment by guilhermedelyra** [comment]
Resolvi
