### ISSUE TITLE
Por que esse tanto de branches???

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-Reabilitacao-Motora#142]
10 alunos -> 38 branches  (?)

**Comment by RomeuCarvalhoAntunes** [comment]
Não tinha percebido o excesso de branches erradas, retirarei as erradas. mas estamos trabalhando com a política de branch cada feature nova é separada pra desenvolvimento em branches.

**Comment by arthurbdiniz** [comment]
Como está o andamento de retirar as branches erradas @RomeuCarvalhoAntunes ?

**Comment by RomeuCarvalhoAntunes** [comment]
Todas as Branches erradas foram retiradas do projeto, peço desculpa pela demora.
