### ISSUE TITLE
Prevenção a SQL Injection

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-gpp-mds/2018.1-Reabilitacao-Motora#147]
### Descrição:
Tratamento do dado inserido em todos os *InputFields* de forma que garanta a segurança e integridade do banco de dados.

### Critérios de Aceitação

- [ ] Build passando
- [ ] Aprovação do Codacy

### Tarefas

- [ ] Tratar as SQL Injections [mais conhecidas](https://www.owasp.org/index.php/Testing_for_SQL_Injection_(OTG-INPVAL-005))

**Comment by victorcmoura** [comment]
Issue sendo fechada pois:
- Não foi possível reproduzir um ataque de SQL Injection;
- Unity possui proteção interna contra este tipo de ataque;
