### ISSUE TITLE
Testes Unity

### ISSUE THREAD

**Issue by lucasssm** [fga-gpp-mds/2018.1-Reabilitacao-Motora#148]
#### Descrição:
Aprendizado e criação dos primeiros testes unitários realizados na plataforma do projeto

#### Critérios de Aceitação
- [x] Aprendizado de implementação de testes
- [x] Capacidade de disseminar o conhecimento para o resto do time.

#### Tarefas
- [x] Verificar viabilidade técnica dos testes.
- [x] Descobrir como implementar os testes unitários na plataforma.
- [ ] Criar um modo para distribuir o conhecimento entre os membros do time
- [ ] Adicionar os testes na integração contínua do projeto.

**Comment by RomeuCarvalhoAntunes** [comment]
Rapaziada, quando abrir issue usar template de issue não de PR....
