### ISSUE TITLE
Adequação com a identidade visual do protótipo.

### ISSUE THREAD

**Issue by lucasssm** [fga-gpp-mds/2018.1-Reabilitacao-Motora#149]
#### Descrição:
Adequação da identidade visual do projeto apresentado na R1 com a identidade visual do protótipo de alta fidelidade.

#### Critérios de Aceitação

- [x] Telas refatoradas.
- [x] Funcionalidades intactas.
- [x] Banco de dados funcional.

#### Tarefas
- [x] Adequar o projeto a nova paleta de cores.
- [x] Refatorar telas já existentes do projeto.
- [x] Cria telas faltantes.
- [x] Excluir telas excedentes.

**Comment by RomeuCarvalhoAntunes** [comment]
Rapaziada, quando abrir issue usar template de issue não de PR....
