### ISSUE TITLE
Pesquisar propostas de implementação TCP/UDP para central de processamento

### ISSUE THREAD

**Issue by lucasssm** [fga-gpp-mds/2018.1-Reabilitacao-Motora#151]
Como requisitado pelo cliente, devemos propor uma forma de conexão entre módulos de processamento externos e nossa aplicação.

**Comment by RomeuCarvalhoAntunes** [comment]
Gerar Documentação explicando vantagens e desvantagens a respeito das conexões TCP/UDP
