### ISSUE TITLE
Implementar Teste 

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#152]
# INTEGRAÇÃO CONTINUA NO DEPLOY
# Pontuação 13 Pontos.

### Descrição:
Incrementa a integração continua com teste unitários e deploy 

### Critérios de Aceitação
- [ ] Sscript de teste no travis passando com algum teste base.
- [ ] Script de deploy do travis passando
- [ ] Apos a finalização do deploy fazer o upload do executavel em algum lugar

### Tarefas
- [ ] Fazer script de teste no travis.
- [ ] Fazer script de deploy do travis
- [ ] Apos a finalização do deploy fazer o upload do executavel em algum lugar

**Comment by RomeuCarvalhoAntunes** [comment]
Separar a Issue em 2.
