### ISSUE TITLE
Launcher para controlar versionamento

### ISSUE THREAD

**Issue by lucasssm** [fga-gpp-mds/2018.1-Reabilitacao-Motora#169]
### Descrição:
Um launcher para controle de versão da aplicação é necessário.

### Critérios de Aceitação
- [ ] Launcher atualizando de acordo com a versão mais atual

### Tarefas
- [x] Launcher verificando a versão instalada
- [ ] Launcher verificando a versão mais recente
- [x] Launcher baixando e instalando a versão mais recente

**Comment by arthurbdiniz** [comment]
Primeira versão nao otimizada do launcher ja está disponivel no link: https://github.com/arthurbdiniz/Launcher.
Versão conta com função de download das builds vindas da api, descompactação do aquivo .zip e execução da aplicação.

**Comment by arthurbdiniz** [comment]
Repositório deve ser transferido para a disciplina fga-gpp-mds
