### ISSUE TITLE
Documento de Visão

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#17]
### Descrição:
Fazer o documento de visão

### Critérios de Aceitação
- [x] O documento deve ser feito em Português.
- [x] Todos os campos devem estar preenchidos 

### Tarefas
- [x] [Introdução](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/wiki/Documento-de-Vis%C3%A3o/#1)
- [x] [Posicionamento](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/wiki/Documento-de-Vis%C3%A3o/#2)
- [x] [Descrições da parte interessada e dos Usuários](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/wiki/Documento-de-Vis%C3%A3o/3)
- [x] [Visão Geral do Produto](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/wiki/Documento-de-Vis%C3%A3o/#4)
- [x] [Recursos do Produto](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/wiki/Documento-de-Vis%C3%A3o/#5)
- [x] [Restrições](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/wiki/Documento-de-Vis%C3%A3o/#6)

**Comment by djorkaeffalexandre** [comment]
Revisem o documento de visão, está finalizado. @victorcmoura

**Comment by RomeuCarvalhoAntunes** [comment]
Revisão final do documento realizada hoje, alterações foram requisitadas, esperando MDS concluí-las para fechar a Issue
