### ISSUE TITLE
Termo de Abertura do Projeto

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#18]
### Descrição:
Produzir termo de abertura do projeto que irá conter um contexto geral do projeto, seus custos e riscos.

### Critérios de Aceitação
- [x] O documento deve estar em Português
- [x] O versionamento do documento deve estar devidamente preenchido
- [x] O documento deve ser revisado
- [x] O documento deve conter referências bibliográficas

### Tarefas
- [x] Propósito ou Justificativa do Projeto
- [x] Objetivos do Projeto
- [x] Descrição do Projeto em alto nível
- [x] Requisitos de alto nível
- [x] Premissas
- [x] Restrições
- [x] Limites do Projeto
- [x] Riscos de alto nível
- [x] Resumo do cronograma de marcos
- [x] Resumo do orçamento
- [X] Equipe de Desenvolvimento de <i>Software</i>
- [x] Requisitos para aprovação do Projeto
- [X] Gerente do Projeto
- [X] Patrocinador
- [X] Responsável pela autorização do Projeto
- [x] Referências bibliográficas

**Comment by vitorfhc** [comment]
Estou trabalhando nos tópicos 1 e 2

**Comment by RomeuCarvalhoAntunes** [comment]
Irei fechar os tópicos faltantes hoje.

**Comment by RomeuCarvalhoAntunes** [comment]
Documento revisado em completo nos tópicos que estavam faltando.
