### ISSUE TITLE
Melhorar exibição dos logs de teste no Travis

### ISSUE THREAD

**Issue by victorcmoura** [fga-gpp-mds/2018.1-Reabilitacao-Motora#182]
# Melhorar exibição dos logs de teste no Travis
---
### Descrição:
Atualmente, os logs de teste estão em formato xml e sendo exibidos no stdout com uma formatação que dificulta a leitura.

### Critérios de Aceitação

- [x] Melhorar visualmente a exibição dos resultados dos testes
- [x] Não quebrar a build

### Tarefas

- [x] Script que exiba o arquivo xml de uma forma amigável

**Comment by RomeuCarvalhoAntunes** [comment]
Tarefa concluída... PR será feito até a 00:00 do dia 23/05/2018

**Comment by RomeuCarvalhoAntunes** [comment]
Reabrindo a issue para arrumar a exibição dos erros do test, no caso de falha
