### ISSUE TITLE
Não estão gerando releases ao fim das sprints

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-Reabilitacao-Motora#183]
gerar relase notes ao fim de cada sprint é uma boa pratica (a curto prazo) para mostrar a evolução da aplicação e tracking dos bugs etc.. além de uma boa ferramenta de transparencia

**Comment by victorcmoura** [comment]
Ao fim da Sprint 12, o deploy contínuo se normalizou junto a um bugfix que impedia o correto funcionamento das builds enviadas para a API de versionamento. Antes, a build estava sendo exportada sem as dependências devidas e, por conta disso, não ocorria conexão com o banco de dados, inutilizando todas as funcionalidades e justificando o não lançamento de uma nova versão.

Com as devidas correções, podemos iniciar um movimento melhor para o lançamento de releases.

https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/releases/tag/0.5
