### ISSUE TITLE
Atenção ao burndown

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-Reabilitacao-Motora#184]
O burndown de vcs está constamente caindo no final da sprint, e ficaram muito tempo sem entregar valor.

Ou,

estão trabalhando de ultima hora 

E/Ou,

estão planejando mal as histórias (não estão atômicas o suficiente para ser queimada para sprint)

E/Ou,

Estão fazendo má gestão dos riscos do projetos (tanto técnico, quanto da equipe)

**Comment by arthurbdiniz** [comment]
@RochaCarla conforme foi possível observar na [Sprint 13](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/issues/184#reports), conseguimos melhorar o burndow devido a um melhor foco do time. Além disso percebemos que as historias não estavam muito atômicas como levando por você. Com base nisso quebramos em historias menores ainda para ter um melhor controle e percebemos que esse risco foi resolvido. Sobre a gestão dos riscos estamos trabalhamos pra alcançar o burndown o máximo escadinha possível. 

![burndown2](https://user-images.githubusercontent.com/18387694/41210571-ff1bd906-6d08-11e8-8320-c28e6cb80cd5.png)

![burndown](https://user-images.githubusercontent.com/18387694/41210532-c8172d48-6d08-11e8-9d07-2c20f670b042.png)
