### ISSUE TITLE
US 16 - Menu de ajuda

### ISSUE THREAD

**Issue by victorcmoura** [fga-gpp-mds/2018.1-Reabilitacao-Motora#192]
# US 16 - Menu de ajuda

### Descrição:
Eu, como fisioterapeuta, desejo ter acesso a um ambiente de suporte para me auxiliar na operação do software.

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Testes passando
- [ ] Build passando

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [ ] Menu de ajuda contendo informações para o usuário

**Comment by lucasssm** [comment]
Esse menu deve conter:
-  Como criar conta de usuário (Fisioterapeuta)
- Como cadastrar pacientes
- Como cadastrar movimentos
- Como realizar uma sessão (Aqui pode destrinchar em mais tópicos, se necessário)
Qualquer adicional que vocês pensarem também é bem vindo.
Lembrem-se que essa parte influencia diretamente na satisfação do usuário, façam bem cheiroso!

**Comment by jlucassr** [comment]
Um detalhe, O Menu de ajuda se apresenta após o cadastro e o login do fisioterapeuta, onde devemos também detalhar como criar o novo Fisioterapeuta, então há duas soluções:
1 - Criamos uma botão de ajuda também na scene de Login.
2 - A cada Scene há um botão de ajuda detalhando como cadastrar/criar seu respectivo conteúdo.

**Comment by victorcmoura** [comment]
@jlucassr, acredito que deve ser apenas uma das opções do menu principal contendo instruções para atividades do tipo:
- Como cadastrar um novo paciente
- Como cadastrar um movimento
- Como rotular um movimento
- Como realizar a sessão de um paciente
- Como consultar o resultado das sessões

**Comment by guilhermesiqueira** [comment]
@jlucassr , visto que já há um ícone que instância um popUp com instruções na scene de cadastro de fisioterapeuta e paciente, pode-se incrementar aquele popUp com informações que você julgar necessárias. Quanto há ter um botão de ajuda em cada scene, não julgo ser uma boa escolha, pois compromete a estética minimalista do front do projeto. A melhor escolha seria a apresentada no comentário do @victorcmoura

**Comment by jlucassr** [comment]
Concordo com o que tenha a dizer @guilhermesiqueira, também creio que o @victorcmoura tenha comentado seja a melhor opção mesmo. Pretendo deixar bem visual o menu de ajuda para enriquecer mais o trabalho. Gostaria que o @lucasssm comente sua opinião do caso.

**Comment by victorcmoura** [comment]
Julgo que ambas as soluções podem ser implementadas de forma simultânea.
