### ISSUE TITLE
Tutorial de criação de paciente com bug de nao conseguir voltar

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#210]
### Descrição:
Ao entrar na pagina de tutorial sobre a criação de novos paciente não consegui voltar para o menu.

![nao e possivel voltar no tutorial de criacao de novos pacientes](https://user-images.githubusercontent.com/18387694/40921706-9c409ec4-67e6-11e8-8d33-cd35f0baba52.png)

### Critérios de Aceitação
- [x] Ao clicar no botão conseguir voltar
- [x] Build passando
- [x] Testes passando   

### Tarefas
- [x] Analisar causa do bug
- [x] Corrigir bug

Obs: possível sobreposição pode estar causando o bug

**Comment by jlucassr** [comment]
Realmente a observação que o @arthurbdiniz levantou fez sentido. Após a remoção do bug do paciente cadastrado no menu de ajuda, o botão de retornar da página está fazendo sua devida função.

**Comment by arthurbdiniz** [comment]
@jlucassr , assim que for possível subir um pull request para fazer a analise da correção

**Comment by victorcmoura** [comment]
Issue fechada no PR #246
