### ISSUE TITLE
Não há avisos sobre erros durante o cadastro de fisioterapeuta

### ISSUE THREAD

**Issue by lucasssm** [fga-gpp-mds/2018.1-Reabilitacao-Motora#211]
### Descrição:
![cadatrar](https://user-images.githubusercontent.com/16053704/40921853-040eab90-67e7-11e8-9f0c-83ef7577ba3e.PNG)
Não há avisos específicos para os erros indicados em vermelho durante o cadastro de conta de fisioterapeuta. Necessita-se:
- [ ] Criar um pop-up explicando o porque do preenchimento de tal campo ser inválido

**Comment by arthurbdiniz** [comment]
Eu prefiro que seja feito um popup genérico que contenha o erro especifico de cada campo. Caso o erro seja em mais de um campo apenas o erro do primeiro campo vai aparecer e se o usuário resolver apenas o primeiro o erro continua descendo ate que tudo seja solucionado.

**Comment by arthurbdiniz** [comment]
Tenta fazer de alguma forma que de para passar a mensagem como parâmetro antes de mostrar. Acho que assim fica melhor e deixa o código mais limpo.

**Comment by guilhermedelyra** [comment]
Como assim antes de mostrar?

**Comment by guilhermedelyra** [comment]
Embora no meu PC não esteja dando problemas (vide fotos)

![screenshot_318](https://user-images.githubusercontent.com/23236957/40991090-144d8912-68c9-11e8-8808-9eef183e53b4.png)
![screenshot_317](https://user-images.githubusercontent.com/23236957/40991091-14704eb6-68c9-11e8-9bcf-f4402c349236.png)
![screenshot_316](https://user-images.githubusercontent.com/23236957/40991092-149336ec-68c9-11e8-9e54-e7d8ab98e550.png)

no do Moura tá dando um erro estético; alguém poderia checar se o mesmo ocorre em vossos computadores?
![photo_2018-06-04_23-17-52](https://user-images.githubusercontent.com/23236957/40991181-514f08ea-68c9-11e8-8d38-927347d163f1.jpg)

**Comment by arthurbdiniz** [comment]
Sobre esse problema de layout só acontece no meu quando deixo no Free Aspect
* Free Acpect
![free](https://user-images.githubusercontent.com/18387694/40993518-34001070-68d0-11e8-927d-10e6da6c7445.png)

* 16:9
![asdasd](https://user-images.githubusercontent.com/18387694/40993517-315257c0-68d0-11e8-9dc0-9f57454e6f4d.png)

**Comment by arthurbdiniz** [comment]
Mas ainda sim a issue não foi completa pois teria que ser feita a correção de aparecer apenas a mensagem de erro especifica para o primeiro campo de erro.

**Comment by arthurbdiniz** [comment]
Um detalhe importante a ser relatado e pedido é que ao abrir um branch sobre uma issue tenta identificar melhor como por exemplo ````issue-211-erros-cadastro``` assim fica mais fácil de ver qual a issue em que devo dar checkout para ver o andamento da resolução.

**Comment by victorcmoura** [comment]
Solicito criação de um Pull Request para facilitar o rastreio dos commits e das branches envolvidas na issue.

**Comment by guilhermedelyra** [comment]
Beleza
