### ISSUE TITLE
Botão de retorno não funciona - Seleção de Sensor

### ISSUE THREAD

**Issue by lucasssm** [fga-gpp-mds/2018.1-Reabilitacao-Motora#215]
### Descrição
![botao de voltar esta muito pequeno](https://user-images.githubusercontent.com/16053704/40922353-5d8486ee-67e8-11e8-8676-c02e38f68248.png)

O botão de retornar não está funcionando na tela de seleção de Sensor. Necessita-se:
- [ ] Tornar o botão de retorno funcional.

**Comment by davialvb** [comment]
Esse problema foi resolvido no PR "correção de bugs UDP". Porem está para ser aprovada.

**Comment by arthurbdiniz** [comment]
Assim que for aprovado vou rodar novamente para verificar @davialvb
