### ISSUE TITLE
Tela de salvar sensor não volta para o menu inicial ao salvar o sensor a ser utilizado

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#217]
### Descrição:
Ao entrar na tela de seleção sensores e clicar em salvar a aplicação vai para tela de gravação de movimento onde apenas deveria voltar para o menu iniciar e salvar a instancia do sensor a ser usado.
 Além disso a tela de gravação em que o usuário é levado nao é possivel voltar e nem um campo desformatado perto da localização de voltar.

![indo para gravar movimento ao invez de voltar para o menu](https://user-images.githubusercontent.com/18387694/40922384-6a633982-67e8-11e8-9047-e3bd7f38219b.png)

![gravar movimento](https://user-images.githubusercontent.com/18387694/40922395-70e9c366-67e8-11e8-9320-0ddc41975ae8.png)

### Critérios de Aceitação
- [x] Após salvar um sensor voltar para o menu
- [x] Arrumar a tela de gravação que o usuário é levado
- [x] Build passando
- [x] Testes passando   

### Tarefas
- [x] Analisar causa do bug
- [x] Corrigir bug

**Comment by davialvb** [comment]
Esse problema foi resolvido na branch "correção de bugs UDP". Porem está para ser aprovada.

**Comment by arthurbdiniz** [comment]
Assim que for aprovado vou rodar novamente para verificar @davialvb
