### ISSUE TITLE
Botão salvar, na tela de escolha de sensor, muito pequeno

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#218]
### Descrição:
Ao entrar na tela de seleção sensores o botão de salvar está muito pequeno comparado ao de outras telas.

![](https://user-images.githubusercontent.com/18387694/40922766-670df618-67e9-11e8-8f49-ac81def059ad.png)

### Critérios de Aceitação
- [x] Botão com tamanho proporcional
- [x] Build passando
- [x] Testes passando   

### Tarefas
- [x] Fazer correção

**Comment by davialvb** [comment]
Esse problema foi resolvido no PR "correção de bugs UDP". Porem está para ser aprovada.

**Comment by arthurbdiniz** [comment]
Assim que for aprovado vou rodar novamente para verificar @davialvb
