### ISSUE TITLE
Criação do adapter para o sensor do cliente

### ISSUE THREAD

**Issue by victorcmoura** [fga-gpp-mds/2018.1-Reabilitacao-Motora#221]
# Criação dos adapters para o código do cliente

### Descrição:
Criação do adapters necessário para se acoplar o sensor do cliente ao projeto.

### Critérios de Aceitação
- [ ] Adapters criados
- [ ] Adapters funcionando

### Tarefas
- [x] Estudos sobre o código
- [ ] Criação do adapter do módulo do sensor

**Comment by victorcmoura** [comment]
O adapter do módulo de processamento deve possuir sua própria issue, pois requere uma solução mais complexa que torna esta issue excessivamente grande. A descrição da issue foi atualizada para condizer com o seu real objetivo.

**Comment by arthurbdiniz** [comment]
Conforme foi decidido pela equipe, foi definido o uso de um celular rodando android para utilizarmos de sensores como giroscópio e acelerômetro ao invés de usar a IMU disponibilizada pelo professor Renato.

* Porque decidimos usar um aparelho android?
A integração com o android em relação aos seus sensores e mais fácil do que com o raspberry pi possibilitando um desenvolvimento mais rápido e com uma melhor integração continua já que possui muita documentação sobre

* Iremos cancelar totalmente o sensor IMU?
No momento ainda não, estaremos apenas priorizando um desenvolvimento que irá render mais e agregar mais valor para o cliente

O repositório do projeto android conta com a captação do dados dos sensores e envio por meio de comunicação UDP e já tem uma versão funcional básica disponível em [Reabilitacao-Motora-UDP-App-Android](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora-UDP-App-Android)

Por esse motivo estarei fechando a issue e caso decidir posteriormente também usar o modulo IMU reabriremos em outra issue.
