### ISSUE TITLE
Comportar multíplos botões

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-gpp-mds/2018.1-Reabilitacao-Motora#226]
### Descrição:
Ao cadastrar-se vários pacientes/movimentos/exercícios/fisioterapeutas, os botões são instanciados fora da tela. O ideal seria ter uma barra de rolagem para poder visualizar todos os botões independente da quantidade.

### Critérios de Aceitação

- [ ] Build passando

### Tarefas

- [ ] Painéis comportando múltiplos botões
- [ ] Painéis com barra de rolagem
- [ ] Correção dos painéis de observações/descrição

**Comment by arthurbdiniz** [comment]
Tem algum exemplo visual @guilhermedelyra ?

**Comment by guilhermedelyra** [comment]
Sim! Perceba como a ultima pessoa, no banco de dados (Jajajaja Kakakaka), não aparece na lista de fisioterapeutas

![screenshot_323](https://user-images.githubusercontent.com/23236957/41009836-e424a3a6-6909-11e8-8ebc-e5e1df776271.png)
![screenshot_322](https://user-images.githubusercontent.com/23236957/41009837-e4463296-6909-11e8-8664-6107553c3187.png)

**Comment by jlucassr** [comment]
Um erro a mais que está acontecendo é que se o conteúdo da descrição de um paciente ou de uma sessão for muito extensa a informação não fica exatamente no local, extrapolando o tamanho da informação e o espaço devido dela. O mesmo acontece com a descrição de um novo movimento.

![sem titulo](https://user-images.githubusercontent.com/23347866/41132810-895b600e-6a99-11e8-8437-8a5255466ba6.png)
