### ISSUE TITLE
Campo de texto com entrada de teclado duplicada

### ISSUE THREAD

**Issue by victorcmoura** [fga-gpp-mds/2018.1-Reabilitacao-Motora#270]
**Descrição do bug**
Em computadores com Ubuntu (unica distro que apresentou problemas até agora), os campos de texto estão duplicando as letras inseridas pelo teclado.

**Reprodução do bug**
1. Acesse o software por meio de uma máquina com Ubuntu
2. Insira um texto em qualquer campo de texto
3. Veja o erro

**Comportamento esperado**
Não ter letras duplicadas

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 17.10

**Comment by guilhermedelyra** [comment]
Se estiver de facil acesso para ti, poderia tirar print?
