### ISSUE TITLE
Não é possível visualizar corretamente os movimentos executados na sessão

### ISSUE THREAD

**Issue by victorcmoura** [fga-gpp-mds/2018.1-Reabilitacao-Motora#275]
# Não é possível visualizar corretamente os movimentos executados na sessão

### Descrição:
Atualmente, a cena de visualizar o movimento realizado na sessão não possui nem o gráfico apresentando o movimento realizado nem a execução do movimento em si. Além disso há dois modelos 3D que, pela falta de informações, não possuem razão para serem duplicados.

![image](https://user-images.githubusercontent.com/26290053/41264972-2ca8bafc-6dc6-11e8-988a-3f23a1b7c06f.png)

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Testes passando
- [ ] Build passando

### Tarefas
- [ ] Apresentar gráfico do movimento realizado
- [ ] Apresentar gráfico do movimento ideal

**Comment by guilhermedelyra** [comment]
Essa issue também já foi resolvida
