### ISSUE TITLE
Tela de gravação de movimento não possui botão salvar

### ISSUE THREAD

**Issue by victorcmoura** [fga-gpp-mds/2018.1-Reabilitacao-Motora#277]
# Tela de gravação de movimento não possui botão salvar
---
### Descrição:
Atualmente, após gravar o movimento, o usuário deve clicar para voltar à scene anterior. Não existe confirmação de que o movimento foi gravado e é contra intuitivo ele voltar para a cena anterior. Deve haver um botão salvar para indicar um fluxo que dê a ideia de que o movimento foi salvo.

![image](https://user-images.githubusercontent.com/26290053/41265096-e12d686a-6dc6-11e8-863b-974e3a57fed2.png)

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Testes passando.
- [ ] Build passando

### Tarefas
- [ ] Criar botão "Salvar"

**Comment by arthurbdiniz** [comment]
Corrigido no PR #286
