### ISSUE TITLE
Formatar nome da sessão

### ISSUE THREAD

**Issue by victorcmoura** [fga-gpp-mds/2018.1-Reabilitacao-Motora#278]
# Formatar nome da sessão

### Descrição:
Atualmente, o nome da sessão é a data descrita no formato YYYY-MM-DD-HH-MM

Deve-se ter uma formatação do tipo HH:MM - DD/MM/YYYY

![image](https://user-images.githubusercontent.com/26290053/41265167-47111208-6dc7-11e8-87b0-74662693fa60.png)

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Testes passando.
- [ ] Build passando
- [ ] Acabou a criatividade

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [ ] Formatar a data

**Comment by arthurbdiniz** [comment]
Corrigido no PR #286
