### ISSUE TITLE
US03 - Executar movimentos

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#29]
# US 03 - Executar movimentos
---
### Descrição:
**Eu, como** fisioterapeuta **desejo** executar movimentos **para** espelhar virtualmente a atividade em um modelo tridimensional .

### Critérios de Aceitaçã:
- [x] Testes Unity passando.

### Tarefas
- [x] Inserir modelo tridimensional que seja compatível com o esqueleto movido pelo sensor.
- [x] Validar movimentação do modelo com feedback em tempo real.

**Comment by djorkaeffalexandre** [comment]
Ficará melhor implementar os gráficos do movimento em uma scene diferente ou na mesma scene que captura os movimentos? @arthurbdiniz @victorcmoura

**Comment by lucasssm** [comment]
Minhas opinião, não sei se o Moura e o Diniz concordam mas: se não tem um empecilho técnico que dificulte muito implementar os gráficos em scenes diferentes, é melhor deixar separado por questões de modularização

**Comment by victorcmoura** [comment]
Concordo com o @lucasssm mas com uma ressalva: Por enquanto, podemos implementar em scenes separadas, mas tenho algumas suspeitas de que implementar o gráfico sendo gerado em tempo real na scene que captura os movimentos ia ser uma feature legal. Para evitar o overhead, no momento, as scenes separadas parecem uma boa abordagem. =)
