### ISSUE TITLE
Botão sumindo

### ISSUE THREAD

**Issue by RomeuCarvalhoAntunes** [fga-gpp-mds/2018.1-Reabilitacao-Motora#300]
# Botões sumindo

---
### Descrição:
Quando percorremos o fluxo de telas ( Pacientes --> "Qualquer paciente"--> Sessões --> Ver Exercícios --> escolhemos a sessão ) não existem os botões iniciais de cadastro
![image](https://user-images.githubusercontent.com/18054053/41323843-735b89ea-6e87-11e8-9a4a-74b57efa1986.png)
O comportamento esperado é 
![image](https://user-images.githubusercontent.com/18054053/41323857-7f131a64-6e87-11e8-9f22-955db7bee155.png)
Este comportamento pode ser alcançado se entrarmos em um exercício previamente cadastrado e clicarmos na seta para voltar para a página anterior.

Outro ponto é fluxo completamente confuso. quando entramos em um movimento e voltamos, ao invés de voltarmos para uma lista de movimentos da sessão voltamos para uma página chamada sessões 
![image](https://user-images.githubusercontent.com/18054053/41323970-327522e6-6e88-11e8-809f-6cbc1306690c.png)
![image](https://user-images.githubusercontent.com/18054053/41323975-38f2fbac-6e88-11e8-8a16-404c6d5ed860.png)

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Testes Unit passando.
- [ ] Arrumar o fluxo de telas
- [ ] Arrumar botões que estão sumindo

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [ ] Realizar playTests adequados
- [ ] Arrumar o fluxo de telas
- [ ] Arrumar botões

**Comment by guilhermedelyra** [comment]
Os dois problemas apontados já foram resolvidos. Infelizmente não sei em qual PR...
