### ISSUE TITLE
Limpar Banco de dados

### ISSUE THREAD

**Issue by RomeuCarvalhoAntunes** [fga-gpp-mds/2018.1-Reabilitacao-Motora#303]
# Limpar o banco de dados
---
### Descrição:
Para testes foram realizadas diversas adições no banco de dados do projeto. Quando subir o PR verificar se o produto já não está vindo com o banco previamente populado.
![banco populado](https://user-images.githubusercontent.com/18054053/41324335-6360309c-6e8a-11e8-9cd6-e4f04f1b48d2.png)

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Testes Unit passando (PlayTests).
- [ ] Produto sem banco de dados

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [ ] Limpar banco de dados do produto

**Comment by jlucassr** [comment]
Rodei um novo PlayTest e aparentemente alguém já limpou o banco de dados. Alguém me confirma fazendo o favor.
