### ISSUE TITLE
Exibição de resultados (Personagens) 

### ISSUE THREAD

**Issue by RomeuCarvalhoAntunes** [fga-gpp-mds/2018.1-Reabilitacao-Motora#304]
# Exibição de resultados (Personagens) 
---
### Descrição:
Na exibição de resultados dos exercícios as imagens dos bonecos do kinect estão desformatadas, desalinhadas e não condizentes. As vezes os bonecos que eram para serem iguais são diferentes as vezes estão em tamanhos desproporcionais.
![resultado do movimento](https://user-images.githubusercontent.com/18054053/41324425-ccd8a91e-6e8a-11e8-952d-13247e0e604f.png)

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Testes Unit passando (PlayTests).
- [ ] Tela refatorada e arrumada.

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [ ] Arrumar formatação dos bonecos

**Comment by guilhermedelyra** [comment]
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
