### ISSUE TITLE
ID Lista de Exercícios

### ISSUE THREAD

**Issue by RomeuCarvalhoAntunes** [fga-gpp-mds/2018.1-Reabilitacao-Motora#306]
# ID Lista de Exercícios
---
### Descrição:
Caso seja necessário mostrar o id do exercício específico da sessão, que ao meu ver não é. Reformatá-lo e zerá-lo pois a numeração está totalmente não condizente. 
![image](https://user-images.githubusercontent.com/18054053/41324492-2bb4765c-6e8b-11e8-880d-70841c4faac6.png)

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Testes Unit passando.
- [ ] Tela refatorada
- [ ] Id's arrumados

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [ ] Arrumar ids
- [ ] Refatorar tela

**Comment by jlucassr** [comment]
![sem titulo](https://user-images.githubusercontent.com/23347866/41444650-cd7bdf8a-701a-11e8-9e2c-74063dcb7e22.png)
Seria assim como gostaria?
