### ISSUE TITLE
Tela de movimentos com bug de popup 

### ISSUE THREAD

**Issue by davialvb** [fga-gpp-mds/2018.1-Reabilitacao-Motora#319]
### Descrição:
Ao entrar na tela de movimentos um popup já aparece validando se o usuario deseja mesmo sair mesmo sem ele ter apertado nenhum botão.

![image](https://user-images.githubusercontent.com/34287081/41445375-798c1804-701f-11e8-87f3-fbdb9d692563.png)

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Testes Unit passando.
- [ ] Build passando.
- [ ] PopUp arrumado.

**Comment by djorkaeffalexandre** [comment]
não consegui reproduzir o erro em questão pra corrigir o bug, pode dar mais detalhes do fluxo que deve ser seguido para que o bug seja reproduzido? @davialvb

**Comment by davialvb** [comment]
O erro estava ocorrendo simplesmente ao entrar na tela de "Movimentos".

**Comment by vitorfhc** [comment]
Como o bug não pode ser reproduzido por nenhum terceiro fecharei a issue dando a possibilidade de reabertura dela caso necessário. Caso isso vá acontecer use o template de bugs para ajudar a tratar o problema.
