### ISSUE TITLE
Bug de fluxo entre telas

### ISSUE THREAD

**Issue by davialvb** [fga-gpp-mds/2018.1-Reabilitacao-Motora#365]
### Descrição:
Ao clicar em movimento, era para ir para a tela de escolha do avatar. Porém está indo direto para a tela de movimentos.

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Testes Unit passando.
- [ ] Build passando.
- [ ] fluxo correto.

**Comment by guilhermesiqueira** [comment]
Isso já foi corrigido na branch de refatoração das views. Peço perdão pela falta de transparência. Logo haverá um novo PR contendo essa modificação

**Comment by davialvb** [comment]
Ok. Será fechada a issue então.
