### ISSUE TITLE
Adicionar mais uma User Story como pré-requisito da EP01

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-gpp-mds/2018.1-Reabilitacao-Motora#37]
### Descrição:
Para completar a EP01, além de conseguir conectar o sensor ao sistema (US17), também é necessário que a US03 esteja completa, de forma que seja possível verificar se o esqueleto está sendo movido pelo sensor, ou não.

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Adicionar US03 como pré requisito da EP01

**Comment by victorcmoura** [comment]
Mudei o título da issue para não ser confundida com a Épica, já que a tag dela estava no início.

**Comment by victorcmoura** [comment]
Acredito que não conseguimos passar bem a ideia de cada US. Vamos lá:

US03 - Eu, como fisioterapeuta, desejo executar movimentos para espelhar virtualmente a atividade em um modelo tridimensional.

Explicando a US em outras palavras: Pessoa realiza movimentos e o software os reproduz em tempo real em um modelo 3D (que no nosso caso será, pelo menos inicialmente, o modelo do Mixamo).

Para viabilizar a captura dos dados necessários, não é necessário que exista um modelo humano em 3D. Basta apenas que exista um esqueleto, não necessariamente 3D ou em tempo real, com eixos que possibilitem a medição do ângulo de junta.

Por isso, acredito que devemos manter a EP01 do jeito que está. Concorda?

**Comment by guilhermedelyra** [comment]
Sim
