### ISSUE TITLE
Levantamento para o armazenamento e modelagem de Banco de Dados

### ISSUE THREAD

**Issue by jlucassr** [fga-gpp-mds/2018.1-Reabilitacao-Motora#38]
### Descrição
É preciso fazer um levantamento do Banco de Dados, de forma que seja possível pensar na linguagem, nas entidades, atributos e relacionamentos que serão trabalhados futuramente.

### Critérios de Aceitação
- [ ] Pensar na elaboração do Banco de Dados 

### Tarefas:
- [ ] Criar MER.
- [ ] Criar DER.
- [ ] Gerar Script .sql
- [ ] Criar model do banco no unity

**Comment by victorcmoura** [comment]
Olá, @jlucassr! Acredito que não será necessária a criação de uma US somente para essa tarefa, ao invés disso só modifique o título e o conteúdo da task para que ela não faça referência à criação de uma US mas sim à criação da modelagem em si. Um bom título seria "Criar modelagem inicial do banco de dados". Lembrando que a descrição também deve acompanhar o raciocínio do título.

**Comment by guilhermedelyra** [comment]
Bom, ao modelar o banco deparei-me com algo que considero crucial.
Há de se decidir se o sistema rodado em:

a) uma clínica, onde vários fisioterapeutas utilizarão o mesmo computador/sistema
ou
b) uma máquina pessoal

Ao meu ver, a situação "a" faz muito mais sentido, além de englobar, também, a situação "b".
Caso optemos por desenvolver o sistema visando a situação "a", hei de mudar alguns atributos no ME-R de forma que fisioterapeutas também possuam login/senha.
