### ISSUE TITLE
Criar Quadro de Pareamento

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#40]
### Descrição:
O quadro de pareamento serve para o acompanhamento de quais membros já parearam entre si. O pareamento sempre ocorrerá baseado na competência de cada membro da equipe, ou seja, de acordo com as tecnologias no quadro de conhecimento. Assim, um membro com um conhecimento alto em determinada tecnologia deve parear com um membro que tenha um conhecimento médio ou baixo nessa mesma tecnologia, garantindo assim que o conhecimento nas diversas tecnologias circule por toda a equipe.

### Critérios de Aceitação
- [x]  Conter pareamento da sprint 02
- [x] Tabela tem que ser feita em markdown para facilitar alterações

### Tarefas
- [x] Conter fotos dos integrantes de MDS
- [x] Ter um layout intuitivo

**Comment by lucasssm** [comment]
@arthurbdiniz markdown mesmo? Se quiser eu faço um bonitinho no PS e edito toda sprint

**Comment by lucasssm** [comment]
Utilizar uma ferramenta mais dinâmica e intuitiva nas próximas sprints?
https://lucasssm.github.io/mds-gppairing/
