### ISSUE TITLE
Ambientação na US03 

### ISSUE THREAD

**Issue by guilhermesiqueira** [fga-gpp-mds/2018.1-Reabilitacao-Motora#45]
### Descrição:
É necessário discutir qual a melhor escolha para o ambiente que o "personagem" será submetido. Como primeira opção, pode-se criar um cenário que não lembre uma clinica, e assim possa deixar alguns pacientes (como crianças) mais à vontade durante o tratamento. A outra escolha seria um ambiente claro, com elementos que lembre uma clinica e cause uma maior imersão. 

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita:
- [ ] Decidir qual ambientação será usada.

**Comment by victorcmoura** [comment]
@guilhermesiqueira, mudei o título da issue para não ser confundida com a [US03](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/issues/29)

**Comment by guilhermesiqueira** [comment]
Sugestão de ambiente default genérico aceita.

![basico](https://user-images.githubusercontent.com/30915713/37859122-01a447de-2eee-11e8-993f-14a2b073954d.png)
