### ISSUE TITLE
Feedback 01

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-Reabilitacao-Motora#48]
Alguns feedbacks observados

- [x] Falta a descrição da metodologia adotada, papéis e responsabilidades

- [x] O Roadmap não está feito.  O roadmap vai ser um dos principais artefatos de gestão de risco no projeto de vocês

- [x] Na descrição da sprint, coloquem o link direto para as histórias de usuário (Menos overhead, e melhor rastreio)

- [x] Colocar links para os indicadores pode dificultar a análise da sprint orientada a dados (a verificar se realmente dificulta)

- [x] Sugestão: ao final de cada sprint, colocar uma seção da análise do scrum master, no qual é feito uma análise da produtividade no time baseado nos dados

- [x] Poucos commits de MDS

- [x] Ainda dá pra melhorar as labels

- [x] Roadmap das frentes (devops, arquitetura, scrum master). Com as metas a serem alcançadas

- [x] Olhar o risk burndown. O projeto de vcs tem muitos riscos tecnologicos, então é uma frente que vcs devem dar prioridade, e monitorar continuamente (de forma mais explicita possível)

- [x] Não achei o protótipo de alta fidelidade

**Comment by RomeuCarvalhoAntunes** [comment]
Roadmap foi feito e colocado na pasta docs pela equipe de EPS, como solicitado.

**Comment by RomeuCarvalhoAntunes** [comment]
Os links para os indicadores da sprint como burndown e velocity me auxiliaram em uma análise mais assertiva das nossas sprints .

**Comment by RomeuCarvalhoAntunes** [comment]
Roadmap de todas as frentes fechados até a r1
