### ISSUE TITLE
Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#58]
### Descrição:
Desenvolver um prototipo de alta fidelidade para manter um design pré definido durante todo projeto .

### Critérios de Aceitação
- [x] Prototipo das principais telas que irão conter na release 1.
- [x] Recolher metricas de pelo menos 5 testes.

### Tarefas

- [x] Criar um projeto no [quant-ux](https://www.quant-ux.com)
- [x] Prototipar telas responsivas
- [x] Trabalhar com dados dinâmicos
- [x] Testar telas criadas.

### Ferramenta
Utilizar a ferramenta [quant-ux](https://www.quant-ux.com) para o desenvolvimento.

**Comment by arthurbdiniz** [comment]
Assim que for criado o projeto no quant-ux, enviar o link de compartilhamento e acrescentar os integrantes de EPS para a avaliação do protótipo.

**Comment by djorkaeffalexandre** [comment]
@guilhermedelyra @jlucassr @guilhermesiqueira @davialvb por favor se cadastrem no Quant-ux e me enviem seus emails cadastrados para que eu possa adicionar ao time no protótipo. link: https://www.quant-ux.com

**Comment by guilhermesiqueira** [comment]
Segue o link do desenvolvimento do protótipo de alta fidelidade. https://www.quant-ux.com/#/apps/5aba9811e2fb5334ce2e5d47.html

**Comment by arthurbdiniz** [comment]
Me adicionar no projeto do quant-ux 
Email: arthurbdiniz@gmail.com

**Comment by RomeuCarvalhoAntunes** [comment]
Adicionar como colaborador no protótipo de alta fidelidade: romeucarvalho2009@hotmail.com

**Comment by djorkaeffalexandre** [comment]
Para testar o protótipo de alta fidelidade acesse esse link: https://www.quant-ux.com/test.html?h=a2aa10ax8F5aqFYNrSZUCLeyaj9yuSwzXKZdY4vCDdmoDho3h2LLzjwPM6pu
Para testar e comentar no protótipo de alta fidelidade acesse esse link: https://www.quant-ux.com/share.html?h=a2aa10ax8F5aqFYNrSZUCLeyaj9yuSwzXKZdY4vCDdmoDho3h2LLzjwPM6pu

**Comment by guilhermesiqueira** [comment]
Protótipo de Alta Fidelidade finalizado. Aguardo o feedback do restante do grupo para possíveis melhorias e/ou correção de erros. Para acessar o protótipo e testar, acesse os links postados na mensagem anterior.

**Comment by victorcmoura** [comment]
Protótipo validado. Criem um markdown com o link e instruções de acesso ao protótipo. Commitem esse markdown em uma branch separada e dêem um PR para fecharmos essa issue xD

**Comment by victorcmoura** [comment]
Lembrando que a milestone é a Release 1, podendo existir alterações no protótipo até lá.
