### ISSUE TITLE
Implementação do Banco de dados

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#66]
### Descrição:
Baseado no script e nas modelagens geradas na issue #60 implementar o banco de dados em C# ou javascript.

### Critérios de Aceitação

- [ ] Testes Unit passando.
- [ ] Testes de CRUD do banco.
- [ ] Banco condizente com os modelos gerados

### Tarefas
- [ ] Implemetar
- [ ] Testar
- [ ] Otimizar
- [ ] Abranger o maximo possivel do escopo do projeto

**Comment by jlucassr** [comment]
Sobre os relacionamentos possui, seria bom alterar o nome dos relacionamentos para não ter conflito no banco de dados, certo?

**Comment by jlucassr** [comment]
Porque Sessão possui todas as outras entidades.

**Comment by lucasssm** [comment]
Que tipo de conflito isso geraria? Que eu me lembre o verbo que liga entidades não chega nem a aparecer nas tabelas. Ou eu não me lembro direito? Mostra aí se puder!

**Comment by jlucassr** [comment]
Bem, pelo que eu trabalhei semestre passado acabamos criando as tabelas para os relacionamentos, passando assim as chances estrangeiras as referenciando.

**Comment by jlucassr** [comment]
Chaves*

**Comment by victorcmoura** [comment]
Não vejo necessidade de uma criação de uma nova tabela apenas para as chaves, dado que nenhum relacionamento que envolve a entidade Sessão é um relacionamento n:m. Apenas os relacionamentos n:m exigem a criação de uma tabela separada apenas para as chaves.

**Comment by lucasssm** [comment]
![image](https://user-images.githubusercontent.com/16053704/38176099-095cd78e-35bf-11e8-9b1f-93279b4ba2e5.png)

Um problema notado pelo @victorcmoura nesse DER:
Creio que seja importante criar uma entidade pessoa que se linke no lugar de fisioterapeuta e paciente à movimento. Motivo disso: Evitaria um bando de chaves estrangeiras nulas na tabela de movimentos. Do jeito que está, sempre que um movimento novo é criado por um fisioterapeuta, esse movimento já vem com 2 campos nulos: idPaciente e idMovimentoPai.

**Comment by victorcmoura** [comment]
Ressalto que o problema identificado não é fruto do DER, mas do MER. Além disso, não nos trará grandes prejuízos alterar a modelagem agora já que a implementação ainda não foi integrada ao projeto.

**Comment by guilhermedelyra** [comment]
Bom, eu e o @jlucassr implementamos da forma que sugeriram (fazendo uma generalização), tanto o mer, der e fisico (o ultimo veja aqui: https://github.com/guilhermedelyra/2018.1-Reabilitacao-Motora/blob/database/Banco_de_Dados/fisico.sql)

Ainda não estamos certos de que essa generalização foi necessária; até porque, no DER, ainda há de se estabelecer uma relação entre movimento--paciente e movimento--fisioterapeuta.

Por fim, mantemos dessa forma, com a generalização, ou não?

**Comment by guilhermedelyra** [comment]
A proposito, fiquei com duvida de como implementar uma tabela auto-relacionada no físico...

**Comment by guilhermedelyra** [comment]
Mas, não há uma distinção clara entre os dois (um cadastra e o outro reproduz)? Omitindo-se isso não terá nenhum prejuízo?

**Comment by victorcmoura** [comment]
Não haverá prejuízo para a regra de negócio, dado que podemos filtrar se o executor do movimento é um paciente ou fisioterapeuta e, baseando-se nisso, separamos os movimentos ótimos dos não-ótimos. Outro ponto importante é lembrar que, por conta das dificuldades da sprint anterior, não estamos mais utilizando a política de forks. Por isso, peço para que subam quaisquer trabalhos em uma branch aqui mesmo no repositório.

**Comment by guilhermedelyra** [comment]
Tá bem
