### ISSUE TITLE
Melhorar o Protótipo de Alta Fidelidade

### ISSUE THREAD

**Issue by victorcmoura** [fga-gpp-mds/2018.1-Reabilitacao-Motora#79]
# Melhorar o protótipo de alta fidelidade
---
### Descrição:
O protótipo de alta fidelidade, disponível [aqui](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/blob/development/docs/wiki/Prototipo.md), é uma prévia visual e comportamental do software que está sendo implementado. A sua melhora deve ser constante enquanto não houver total implementação do que está nele previsto.

### Tarefas
- [x] Melhorar protótipo de alta fidelidade

**Comment by victorcmoura** [comment]
Em uma breve conversa com a @RochaCarla, chegamos à conclusão de que ainda há coisas a serem feitas no protótipo de alta fidelidade. Os feedbacks sobre tal artefato serão feitos por meio desta issue.

**Comment by RomeuCarvalhoAntunes** [comment]
Adicionar funcionalidade para todos os  botões do protótipo

**Comment by guilhermesiqueira** [comment]
Protótipo de alta fidelidade melhorado, adequando à nova identidade visual.

Para simples teste, clique [aqui](https://www.quant-ux.com/test.html?h=a2aa10aUbwoaitNtofUizk9iydeBepQG9UZKiRivlnz1DdIWrXJGBP5mM2ze)
Para sugerir melhorias, clique [aqui](https://www.quant-ux.com/share.html?h=a2aa10aUbwoaitNtofUizk9iydeBepQG9UZKiRivlnz1DdIWrXJGBP5mM2ze) e deixe o seu comentário.
