### ISSUE TITLE
Criação de um plano de gerência de riscos

### ISSUE THREAD

**Issue by victorcmoura** [fga-gpp-mds/2018.1-Reabilitacao-Motora#81]
Criação do plano de gerência de riscos
---
### Descrição:
Documento que facilita o controle dos riscos do projeto

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Documento listando os principais riscos do projeto

### Tarefas
- [ ] Levantamento dos riscos do projeto
- [ ] Criação do documento
- [ ] Criação de um burndown dos riscos

**Comment by victorcmoura** [comment]
Como sugestão para controlarmos o *burndown* dos riscos, podemos utilizar o **ZenHub**. Cria-se uma *issue* contendo o risco, a pontuamos de acordo com o nível de importância e a associamos à release. Quando eliminarmos o risco, fecha-se a *issue*. Assim, o **ZenHub** montará o *burndown* de forma automatizada para nós.

**Comment by RomeuCarvalhoAntunes** [comment]
Acho que essa sugestão foi vetada pela professora Carla Rocha. Acho também que deveríamos assinalar esta tarefa como sprint 04 visto que deve ser feito o "Roadmap" de riscos e neste ponto já estamos atrasados. Solicito a relocação da issue e sua devida pontuação

**Comment by RomeuCarvalhoAntunes** [comment]
@victorcmoura  esta tarefa já foi concluída ou não ??
