### ISSUE TITLE
Project Model Canvas

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#90]
### Descrição:
O Business Model Canvas, mais conhecido como Canvas, é uma ferramenta de planejamento estratégico, que permite desenvolver e esboçar modelos de negócio novos ou existentes.

### Critérios de Aceitação
- [x] Todos os campos preenchidos.

### Tarefas
- [x] Parcerias/chave
- [x] Atividades Chave
- [x] Propostas de Valor
- [x] Relacionamento
- [x] Segmentos de Clientes
- [x] Recursos Chave
- [x] Canais 
- [x] Estrutura de Custos
- [x] Fontes de Receitas

**Comment by arthurbdiniz** [comment]
Modelo criado por @lucasssm e eu
![screenshot from 2018-04-04 21-14-35](https://user-images.githubusercontent.com/18387694/38341093-370059dc-384d-11e8-9ad9-aefd9e8c3090.png)

**Comment by arthurbdiniz** [comment]
@victorcmoura, @RomeuCarvalhoAntunes, @vitorfhc poderiam dar uma olhada no modelo?

**Comment by RomeuCarvalhoAntunes** [comment]
Eu tenho visto que o nosso projeto, tem como "público alvo" não só pacientes que sofreram AVC, mas todos aqueles que possuem alguma restrição de movimento nos membros superiores. Então acho válido a troca de "Pacientes que sofreram AVC" por "Pacientes com movimentos dos membros superiores restringidos "

**Comment by arthurbdiniz** [comment]
@RomeuCarvalhoAntunes vamos conversar sobre o assunto e decidir em grupo como seria essa parte de publico alvo?
