### ISSUE TITLE
Feedback 02

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-Reabilitacao-Motora#94]
- [x] Template gipage legal

- [x] Gestão de riscos boa

- [x] Como medir a qualidade do codigo?

- [x] Gitpage esta quebrado (não tem acompanhamento das sprints)

- [x] Canvas - melhorar a visão de produto

**Comment by RomeuCarvalhoAntunes** [comment]
Gitpages arrumado

**Comment by RomeuCarvalhoAntunes** [comment]
@RochaCarla o @victorcmoura está responsável por medir a qualidade do código, acredito que usaremos uma ferramenta de análise estática, que já está sendo testada.

**Comment by RomeuCarvalhoAntunes** [comment]
@RochaCarla a visão de produto no canvas foi tratada pelo @lucasssm que está na elaboração de outro canvas referente apenas a parte de produto, que seria o Product Canvas

**Comment by RomeuCarvalhoAntunes** [comment]
Visão de produto adicionada no repositório, feita pelo @lucasssm
